# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ApiPrecautionsConfig.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'ApiPrecautionsConfig.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x41piPrecautionsConfig.proto\x12\x08protobuf\"\xee\x05\n\x14\x41piPrecautionsConfig\x12#\n\x16\x62ypassOrderPrecautions\x18\x01 \x01(\x08H\x00\x88\x01\x01\x12\x1e\n\x11\x62ypassBondWarning\x18\x02 \x01(\x08H\x01\x88\x01\x01\x12,\n\x1f\x62ypassNegativeYieldConfirmation\x18\x03 \x01(\x08H\x02\x88\x01\x01\x12$\n\x17\x62ypassCalledBondWarning\x18\x04 \x01(\x08H\x03\x88\x01\x01\x12-\n bypassSameActionPairTradeWarning\x18\x05 \x01(\x08H\x04\x88\x01\x01\x12)\n\x1c\x62ypassFlaggedAccountsWarning\x18\x06 \x01(\x08H\x05\x88\x01\x01\x12.\n!bypassPriceBasedVolatilityWarning\x18\x07 \x01(\x08H\x06\x88\x01\x01\x12\'\n\x1a\x62ypassRedirectOrderWarning\x18\x08 \x01(\x08H\x07\x88\x01\x01\x12\'\n\x1a\x62ypassNoOverfillProtection\x18\t \x01(\x08H\x08\x88\x01\x01\x12\'\n\x1a\x62ypassRouteMarketableToBBO\x18\n \x01(\x08H\t\x88\x01\x01\x42\x19\n\x17_bypassOrderPrecautionsB\x14\n\x12_bypassBondWarningB\"\n _bypassNegativeYieldConfirmationB\x1a\n\x18_bypassCalledBondWarningB#\n!_bypassSameActionPairTradeWarningB\x1f\n\x1d_bypassFlaggedAccountsWarningB$\n\"_bypassPriceBasedVolatilityWarningB\x1d\n\x1b_bypassRedirectOrderWarningB\x1d\n\x1b_bypassNoOverfillProtectionB\x1d\n\x1b_bypassRouteMarketableToBBOBD\n\x16\x63om.ib.client.protobufB\x19\x41piPrecautionsConfigProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ApiPrecautionsConfig_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\031ApiPrecautionsConfigProto\252\002\016IBApi.protobuf'
  _globals['_APIPRECAUTIONSCONFIG']._serialized_start=41
  _globals['_APIPRECAUTIONSCONFIG']._serialized_end=791
# @@protoc_insertion_point(module_scope)
