# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AttachedOrders.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'AttachedOrders.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x41ttachedOrders.proto\x12\x08protobuf\"\xb0\x01\n\x0e\x41ttachedOrders\x12\x16\n\tslOrderId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x18\n\x0bslOrderType\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x16\n\tptOrderId\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x18\n\x0bptOrderType\x18\x04 \x01(\tH\x03\x88\x01\x01\x42\x0c\n\n_slOrderIdB\x0e\n\x0c_slOrderTypeB\x0c\n\n_ptOrderIdB\x0e\n\x0c_ptOrderTypeB>\n\x16\x63om.ib.client.protobufB\x13\x41ttachedOrdersProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AttachedOrders_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\023AttachedOrdersProto\252\002\016IBApi.protobuf'
  _globals['_ATTACHEDORDERS']._serialized_start=35
  _globals['_ATTACHEDORDERS']._serialized_end=211
# @@protoc_insertion_point(module_scope)
