# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ConfigResponse.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'ConfigResponse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ibapi.protobuf.LockAndExitConfig_pb2 as LockAndExitConfig__pb2
import ibapi.protobuf.MessageConfig_pb2 as MessageConfig__pb2
import ibapi.protobuf.ApiConfig_pb2 as ApiConfig__pb2
import ibapi.protobuf.OrdersConfig_pb2 as OrdersConfig__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x43onfigResponse.proto\x12\x08protobuf\x1a\x17LockAndExitConfig.proto\x1a\x13MessageConfig.proto\x1a\x0f\x41piConfig.proto\x1a\x12OrdersConfig.proto\"\x87\x02\n\x0e\x43onfigResponse\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x35\n\x0blockAndExit\x18\x02 \x01(\x0b\x32\x1b.protobuf.LockAndExitConfigH\x01\x88\x01\x01\x12)\n\x08messages\x18\x03 \x03(\x0b\x32\x17.protobuf.MessageConfig\x12%\n\x03\x61pi\x18\x04 \x01(\x0b\x32\x13.protobuf.ApiConfigH\x02\x88\x01\x01\x12+\n\x06orders\x18\x05 \x01(\x0b\x32\x16.protobuf.OrdersConfigH\x03\x88\x01\x01\x42\x08\n\x06_reqIdB\x0e\n\x0c_lockAndExitB\x06\n\x04_apiB\t\n\x07_ordersB>\n\x16\x63om.ib.client.protobufB\x13\x43onfigResponseProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ConfigResponse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\023ConfigResponseProto\252\002\016IBApi.protobuf'
  _globals['_CONFIGRESPONSE']._serialized_start=118
  _globals['_CONFIGRESPONSE']._serialized_end=381
# @@protoc_insertion_point(module_scope)
