# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: LockAndExitConfig.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'LockAndExitConfig.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17LockAndExitConfig.proto\x12\x08protobuf\"\xa7\x01\n\x11LockAndExitConfig\x12\x1b\n\x0e\x61utoLogoffTime\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1d\n\x10\x61utoLogoffPeriod\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x1b\n\x0e\x61utoLogoffType\x18\x03 \x01(\tH\x02\x88\x01\x01\x42\x11\n\x0f_autoLogoffTimeB\x13\n\x11_autoLogoffPeriodB\x11\n\x0f_autoLogoffTypeBA\n\x16\x63om.ib.client.protobufB\x16LockAndExitConfigProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LockAndExitConfig_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\026LockAndExitConfigProto\252\002\016IBApi.protobuf'
  _globals['_LOCKANDEXITCONFIG']._serialized_start=38
  _globals['_LOCKANDEXITCONFIG']._serialized_end=205
# @@protoc_insertion_point(module_scope)
