# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: OrdersSmartRoutingConfig.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'OrdersSmartRoutingConfig.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eOrdersSmartRoutingConfig.proto\x12\x08protobuf\"\xf8\x01\n\x18OrdersSmartRoutingConfig\x12!\n\x14seekPriceImprovement\x18\x01 \x01(\x08H\x00\x88\x01\x01\x12\x1b\n\x0epreOpenReroute\x18\x02 \x01(\x08H\x01\x88\x01\x01\x12\"\n\x15\x64oNotRouteToDarkPools\x18\x03 \x01(\x08H\x02\x88\x01\x01\x12\x1d\n\x10\x64\x65\x66\x61ultAlgorithm\x18\x04 \x01(\tH\x03\x88\x01\x01\x42\x17\n\x15_seekPriceImprovementB\x11\n\x0f_preOpenRerouteB\x18\n\x16_doNotRouteToDarkPoolsB\x13\n\x11_defaultAlgorithmBH\n\x16\x63om.ib.client.protobufB\x1dOrdersSmartRoutingConfigProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'OrdersSmartRoutingConfig_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\035OrdersSmartRoutingConfigProto\252\002\016IBApi.protobuf'
  _globals['_ORDERSSMARTROUTINGCONFIG']._serialized_start=45
  _globals['_ORDERSSMARTROUTINGCONFIG']._serialized_end=293
# @@protoc_insertion_point(module_scope)
