# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: UpdateConfigRequest.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'UpdateConfigRequest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ibapi.protobuf.LockAndExitConfig_pb2 as LockAndExitConfig__pb2
import ibapi.protobuf.MessageConfig_pb2 as MessageConfig__pb2
import ibapi.protobuf.ApiConfig_pb2 as ApiConfig__pb2
import ibapi.protobuf.OrdersConfig_pb2 as OrdersConfig__pb2
import ibapi.protobuf.UpdateConfigWarning_pb2 as UpdateConfigWarning__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19UpdateConfigRequest.proto\x12\x08protobuf\x1a\x17LockAndExitConfig.proto\x1a\x13MessageConfig.proto\x1a\x0f\x41piConfig.proto\x1a\x12OrdersConfig.proto\x1a\x19UpdateConfigWarning.proto\"\x83\x03\n\x13UpdateConfigRequest\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x35\n\x0blockAndExit\x18\x02 \x01(\x0b\x32\x1b.protobuf.LockAndExitConfigH\x01\x88\x01\x01\x12)\n\x08messages\x18\x03 \x03(\x0b\x32\x17.protobuf.MessageConfig\x12%\n\x03\x61pi\x18\x04 \x01(\x0b\x32\x13.protobuf.ApiConfigH\x02\x88\x01\x01\x12+\n\x06orders\x18\x05 \x01(\x0b\x32\x16.protobuf.OrdersConfigH\x03\x88\x01\x01\x12\x37\n\x10\x61\x63\x63\x65ptedWarnings\x18\x06 \x03(\x0b\x32\x1d.protobuf.UpdateConfigWarning\x12\"\n\x15resetAPIOrderSequence\x18\x07 \x01(\x08H\x04\x88\x01\x01\x42\x08\n\x06_reqIdB\x0e\n\x0c_lockAndExitB\x06\n\x04_apiB\t\n\x07_ordersB\x18\n\x16_resetAPIOrderSequenceBC\n\x16\x63om.ib.client.protobufB\x18UpdateConfigRequestProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UpdateConfigRequest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\030UpdateConfigRequestProto\252\002\016IBApi.protobuf'
  _globals['_UPDATECONFIGREQUEST']._serialized_start=150
  _globals['_UPDATECONFIGREQUEST']._serialized_end=537
# @@protoc_insertion_point(module_scope)
