# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: UpdateConfigResponse.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'UpdateConfigResponse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ibapi.protobuf.UpdateConfigWarning_pb2 as UpdateConfigWarning__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aUpdateConfigResponse.proto\x12\x08protobuf\x1a\x19UpdateConfigWarning.proto\"\xce\x01\n\x14UpdateConfigResponse\x12\x12\n\x05reqId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x13\n\x06status\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x14\n\x07message\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x15\n\rchangedFields\x18\x04 \x03(\t\x12\x0e\n\x06\x65rrors\x18\x05 \x03(\t\x12/\n\x08warnings\x18\x06 \x03(\x0b\x32\x1d.protobuf.UpdateConfigWarningB\x08\n\x06_reqIdB\t\n\x07_statusB\n\n\x08_messageBD\n\x16\x63om.ib.client.protobufB\x19UpdateConfigResponseProto\xaa\x02\x0eIBApi.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UpdateConfigResponse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.ib.client.protobufB\031UpdateConfigResponseProto\252\002\016IBApi.protobuf'
  _globals['_UPDATECONFIGRESPONSE']._serialized_start=68
  _globals['_UPDATECONFIGRESPONSE']._serialized_end=274
# @@protoc_insertion_point(module_scope)
